# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Amelia Lin
title: Student
email: linameli@msu.edu
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Kiramki

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Amelia and I'm a student at Michigan State University! I'm currently studying computer science - I hope to be able to gain new skills and experience during college to follow my dream of using technology to inspire and connect people. I'm excited to see how I can grow and learn in the future, and am always looking for opportunities to do so! I have worked on a few personal projects in the past, and would love to work on more projects with others in the future.

  I'm most skilled in <mark>Python</mark>, <mark>C++</mark>, and <mark>Thinking of new ideas!</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Book of Hours Catalogue
        link: github.com/Kiramki/kiramki.bohcatalogue.git
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          This is a project I made to aid in gameplay of one of my favorite games, Book of Hours. Book of Hours is a game that takes place in a massive library, where the player obtains and catalogues a wide variety of books, and must use them to gain memories and knowledge to progress in the game. The game itself, however, lacks a built-in catalogue system, so I created this project to help players keep track of the books they have found and read, as well as its contents and what re-reading the book will give them.

          This project was created using Python, and is a command-line interface program. It stores the data in a txt file, and allows the user to add, remove, and view books in their collection. It also features a filtering system, a search function, support for multiple save files, data about the books, and more. 

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigan State University
        caption: 2023 - Present
        sub_title: BS Computer Science
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I am currently a student at Michigan State University, studying computer science. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of my studies, I have a few interests and hobbies, including:

      - Writing, especially with friends!
      - Golf - I was on my high school's varsity golf team for 4 years. We made it to States three times!
      - Playing video games - I love experiencing games with a good story, and I love trying to break them.
      - Coding - Working on personal projects without any pressure is a great way to keep my skills sharp and have a bit of fun!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
